language: python

virtualenv:
    system_site_packages: true

install:
    - sudo apt-get install -qq python-scipy python-nose python-pip python-matplotlib
    - pip install -r requirements.txt
    - pip install --download-cache=. scikit-learn
    - tar xvf scikit-learn*.tar.gz
