language: python

virtualenv:
    system_site_packages: true

install:
    - sudo apt-get install -qq python-scipy python-nose python-pip python-matplotlib
    - pip install --download-cache=. scikit-learn
    - tar xvf $(ls scikit-learn*.tar.gz)
    - pip install -r requirements.txt
