language: python

install:
    - sudo apt-get install optipng
    - deactivate
    - bash mkhtml.sh
    - source ~/virtualenv/python2.7/bin/activate
    - pip install -r requirements.txt
    - cd cache/scikit-learn*/doc/_build/
    - doc2dash -n Scikit-learn html/stable/

script:
    - tar czf Scikit-learn.docset.tgz Scikit-learn.docset/
