language: python

virtualenv:
    system_site_packages: true

install:
    - sudo apt-get install -qq python-scipy python-nose python-pip python-matplotlib
    - pip install -r requirements.txt
    - pip install --download-cache=sklearn.tar.gz
    - tar xvf sklearn.tar.gz
